/* config.h.  Generated by configure.  */
/* config.h.in.  Generated automatically from configure.in by autoheader.  */

/* Define if you don't have vprintf but do have _doprnt.  */
/* #undef HAVE_DOPRNT */

/* Define if you have <vfork.h>.  */
/* #undef HAVE_VFORK_H */

/* Define if you have the vprintf function.  */
#define HAVE_VPRINTF 1

/* Define to `int' if <sys/types.h> doesn't define.  */
/* #undef pid_t */

/* Define to `unsigned' if <sys/types.h> doesn't define.  */
/* #undef size_t */

/* Define if you have the ANSI C header files.  */
#define STDC_HEADERS 1

/* Define vfork as fork if vfork does not work.  */
/* #undef vfork */

/* Define if the X Window System is missing or not being used.  */
/* #undef X_DISPLAY_MISSING */

/* Define if lex declares yytext as a char * by default, not a char[].  */
#define YYTEXT_POINTER 1

/* Define if you want a debug version of qvwm */
/* #undef DEBUG */

/* Define if you allow sending commands to qvwm */
#define ALLOW_RMTCMD 1

/* Define if you want to use Imlib */
/* #undef USE_IMLIB */

/* Define if the X shape extension is available */
#define USE_SHAPE 1

/* Define if the X Session Management Protocol is available */
#define USE_XSMP 1

/* Define if you want to use ALSA for sound effects (Linux only) */
/* #undef USE_ALSA */

/* Define if you want to use esd (EsounD) for sound effects */
/* #undef USE_ESD */

/* Define if you want to use screen saver functions */
#define USE_SS 1

/* Define if the X screen saver extension is available */
#define USE_SSEXT 1

/* Define if the X server supports locale functions */
#define X_LOCALE 1

/* Define if you have the usleep function.  */
#define HAVE_USLEEP 1

/* Name of package */
#define PACKAGE "qvwm"

/* Version number of package */
#define VERSION "1.2.0-pre"

